### ISSUE TITLE
what does the "Name Components" mean?

### ISSUE THREAD

**Issue by qiangshui** [BTplc/grafana-peak-report#1]
I use the "Zabbix" datasource, and I configure Metrics like this:
![image](https://user-images.githubusercontent.com/24819310/29648170-638252f0-88bf-11e7-96ea-2daf22b49127.png)

In the Options like this：
![image](https://user-images.githubusercontent.com/24819310/29648239-b82650c2-88bf-11e7-8122-0562e0b72476.png)
![image](https://user-images.githubusercontent.com/24819310/29648245-c0f3c252-88bf-11e7-99cc-fbc0141a40f0.png)

How I make the "Name" colum dispaly host which configured in the Metrics?

and I don't know how to use the "Name Components"

![image](https://user-images.githubusercontent.com/24819310/29648360-43795ee4-88c0-11e7-9256-e041d22a5d64.png)

Or zabbix datasource can't use this panel?

**Comment by tpbowden** [comment]
The name components are for metrics which are delimited by dots allowing specific parts of the metric name to be used on the panel. I believe this is only supported by Graphite data source however

**Comment by benthorner** [comment]
You could try entering '0' for the name components, but as @tpbowden says, it's only designed to work with Graphite.

**Comment by benthorner** [comment]
Closing as no action required.
